require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses
